version: '3.4'
services:
  leadwire-portail:
    image: leadwire/apm-leadwire-portail:1.0.5
    environment:
      LEADWIRE_ADMIN_PASSWORD: '{SSHA}KrVJR86xuoezxyDgOgrq7haWg2QgPbJ2'
      LEADWIRE_ADMIN_EMAIL: contact@leadwire.io
      LEADWIRE_CLUSTER_NAME: leadwire-cluster
      LEADWIRE_CLUSTER_VERSION: 7.6.1
      LEADWIRE_SETUP_CLUSTER: 'true'
      LEADWIRE_SETUP_DEMO: 'true'
      LEADWIRE_SETUP_LDAP: 'true'
      LEADWIRE_ISM_ROLLOVER_SETUP: 'false'
      LEADWIRE_ISM_DELETE_MIN_INDEX_AGE: 7d
      LEADWIRE_ISM_MIN_SIZE: 5gb
      LEADWIRE_ISM_MIN_DOC_COUNT: 1000000
      LEADWIRE_ISM_MIN_INDEX_AGE: 7d
      LEADWIRE_DATABASE_NAME: leadwire
      LEADWIRE_DATABASE_HOST: leadwire_leadwire-mongodb
      LEADWIRE_DATABASE_PORT: 27017
      LEADWIRE_DATABASE_USER: admin
      LEADWIRE_DATABASE_PASSWORD: admin
      LEADWIRE_APP_DOMAIN: apm.test.leadwire.io
      LEADWIRE_APP_SCHEME: https
      LEADWIRE_SUPER_USER_ADMIN_NAME: admin
      LEADWIRE_MAILER_HOST: smtp.gmail.com
      LEADWIRE_MAILER_PORT: 465
      LEADWIRE_MAILER_TRANSPORT: gmail
      LEADWIRE_MAILER_USER: contact@leadwire.io
      LEADWIRE_MAILER_ENCRYPTION: ssl
      LEADWIRE_MAILER_PASSWORD: changeit
      LEADWIRE_JWT_TOKEN_SECRET: token123456789
      LEADWIRE_KIBANA_HOST: http://leadwire_leadwire-kibana
      LEADWIRE_KIBANA_PORT: 5601
      LEADWIRE_KIBANA_IFRAME_HOST: https://kibana.test.leadwire.io
      LEADWIRE_KIBANA_IFRAME_PORT: 443
      LEADWIRE_KIBANA_ADMIN_USERNAME: admin
      LEADWIRE_KIBANA_ADMIN_UUID: admin
      LEADWIRE_ES_USERNAME: admin
      LEADWIRE_ES_PASSWORD: admin
      LEADWIRE_ES_HOST: https://leadwire_leadwire-node1
      LEADWIRE_ES_PORT: 9200
      LEADWIRE_SOCKET_IO_PORT: 443
      LEADWIRE_SOCKET_DOMAIN: io.test.leadwire.io
      LEADWIRE_SOCKET_SCHEME: https
      LEADWIRE_LOGOUT_URL: https://auth.test.leadwire.io/?logout=1
      LEADWIRE_PLATFORM_NAME: leadwire
      LEADWIRE_LOGIN_METHOD: proxy
      LEADWIRE_COMPAGNE_ENABLED: 'false'
      LEADWIRE_JENKINS_URL: unused
      LEADWIRE_LDAP_HOST: leadwire_leadwire-ldap
      LEADWIRE_LDAP_PORT: 389
      LEADWIRE_LDAP_DN_USER: cn=admin,dc=leadwire,dc=io
      LEADWIRE_LDAP_PASSWORD: admin
      LEADWIRE_GITHUB_CLIENT_SECRET: unused
      LEADWIRE_GITHUB_CLIENT_ID: unused
      LEADWIRE_STRIPE_SECRET_KEY: unused
      LEADWIRE_STRIPE_ENABLED: 'false'
    networks:
      - leadwire-net
    volumes:
      - C:\Users\dhib\VSCodeRepository\leadwire-portail:/usr/share/leadwire-portail/
    depends_on:
      - "leadwire_leadwire-mongodb"
      - "leadwire_leadwire-node1"
      - "leadwire_leadwire-ldap"
  leadwire-socket-io:
    image: leadwire/apm-leadwire-socket.io:1.0.0
    environment:
      LEADWIRE_SSL_KEY: /certificates/server.key
      LEADWIRE_SSL_CERT: /certificates/server.pem
      LEADWIRE_SOCKET_IO_PORT: 9000
    networks:
      - leadwire-net
  leadwire-core:
    image: leadwire/apm-leadwire-core:1.0.0
    depends_on:
      - "leadwire_leadwire-node1"
      - "leadwire_leadwire-kibana"
      - "leadwire_leadwire-alertmanager"
      - "leadwire_leadwire-portail"
      - "leadwire_leadwire-socket-io"
      - "leadwire_leadwire-grafana"
    ports:
      - 80:80
      - 443:443
    environment:
      SSODOMAIN: leadwire.io
      PORTAL_HOSTNAME: auth.test.leadwire.io
      MANAGER_HOSTNAME: manager.test.leadwire.io
      HANDLER_HOSTNAME: reload.test.leadwire.io
      APM_HOSTNAME: apm.test.leadwire.io
      KIBANA_HOSTNAME: kibana.test.leadwire.io
      LOGLEVEL: info
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./.docker/leadwire-core/etc/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - leadwire-net
  leadwire-ldap:
    image: leadwire/apm-leadwire-ldap:1.0.0
    ports:
      - 389:389
    volumes:
      - leadwire-ldapdata:/var/lib/ldap
    networks:
      - leadwire-net
  leadwire-alertmanager:
    image: prom/alertmanager:latest 
    volumes:
      - ./.docker/leadwire-alertmanager/etc/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - leadwire-alertmanagerdata:/etc/alertmanager/data/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--web.external-url=https://alert.test.leadwire.io'
    networks:
      - leadwire-net
  leadwire-mongodb:
    image: mongo:3.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - leadwire-mongodata:/data/db/
    networks:
      - leadwire-net
  leadwire-node1:
    image: amazon/opendistro-for-elasticsearch:1.12.0
    environment:
      - cluster.name=leadwire-cluster
      - node.name=leadwire_leadwire-node1
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - opendistro_security.unsupported.restapi.allow_securityconfig_modification=true
    volumes:
      - leadwire-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - leadwire-net
  leadwire-kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.12.0
    environment:
      ELASTICSEARCH_URL: https://leadwire-node1:9200
      ELASTICSEARCH_HOSTS: https://leadwire-node1:9200
    volumes:
      - .docker/leadwire-kibana/usr/share/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - leadwire-net
  leadwire-grafana:
    image: grafana/grafana:latest
    volumes:
      - leadwire-grafanadata:/var/lib/grafana
      - .docker/leadwire-grafana/etc/grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - leadwire-net
volumes:
  leadwire-data1:
  leadwire-data2:
  leadwire-data3:
  leadwire-mongodata:
  leadwire-grafanadata:
  leadwire-alertmanagerdata:
  leadwire-ldapdata:
  leadwire-coredata:
networks:
  leadwire-net:

